name: Coding Standards

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  coding-standards:
    name: Coding Standards
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.0
          tools: cs2pr
          coverage: none

      - name: Install dependencies
        run: composer install --no-interaction --no-progress --prefer-dist

      - name: Validate composer.json
        run: composer validate --strict

      - name: Run PHP_CodeSniffer
        run: ./vendor/bin/phpcs -q --no-colors --report=checkstyle src tests | cs2pr
